apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true

  - name: MongoDB
    type: mongodb
    access: proxy
    url: mongodb://admin:password@mongodb:27017/pricing?authSource=admin
    database: pricing
    editable: true
