"""initial_migration

Revision ID: 554483b016d0
Revises:
Create Date: 2025-09-28 16:14:58.450926

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "554483b016d0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
